using System;
using System.IO;
using UnityEngine;

/// <summary>
/// FR5 C# Bridge Client
///
/// Role:
/// 1. Read bridge JSON generated by the external C# SDK bridge.
/// 2. Provide the latest runtime sample through IFR5RuntimePoseSource.
/// 3. Expose bridge status fields for UI panels.
/// </summary>
public class scr_FR5CSharpBridgeClient : MonoBehaviour, IFR5RuntimePoseSource
{
    [Serializable]
    private class FR5BridgeSampleJson
    {
        public bool isValid = false;
        public string source = "CSharpBridge";
        public double timestampSeconds = 0.0;

        public float[] jointDegrees = new float[6];
        public float[] flangePositionMillimeters = new float[3];
        public float[] flangeRotationDegrees = new float[3];
        public float[] tcpPositionMillimeters = new float[3];
        public float[] tcpRotationDegrees = new float[3];

        public int toolIndex = -1;
        public int userIndex = -1;
        public string robotMode = "Unknown";
        public string robotState = "Unknown";
        public int alarmCode = 0;
    }

    [Header("Bridge File")]
    [SerializeField] private string bridgeFolderName = "Bridge";
    [SerializeField] private string bridgeFileName = "fr5_live_state.json";
    [SerializeField] private bool autoConnectOnStart = true;

    [Header("Debug")]
    [SerializeField] private bool verboseLog = true;

    [Header("Runtime Status")]
    [SerializeField] private string resolvedBridgeFilePath = string.Empty;
    [SerializeField] private bool lastFileExists = false;
    [SerializeField] private bool lastPollSucceeded = false;
    [SerializeField] private bool lastSampleValid = false;
    [SerializeField] private string lastSampleSource = "None";
    [SerializeField] private string lastRobotState = "Unknown";
    [SerializeField] private string lastPollTime = "-";
    [SerializeField] private string lastErrorMessage = "None";

    private bool isConnected = false;
    private FR5SdkPoseSample latestSample = FR5SdkPoseSample.CreateInvalid("CSharpBridge");
    private string previousLogKey = string.Empty;

    public bool IsConnected => isConnected;
    public bool LastPollSucceeded => lastPollSucceeded;
    public bool LastSampleValid => lastSampleValid;
    public string LastSampleSource => lastSampleSource;
    public string LastRobotState => lastRobotState;
    public string LastPollTime => lastPollTime;
    public string LastErrorMessage => lastErrorMessage;
    public string ResolvedBridgeFilePath => resolvedBridgeFilePath;

    private void Start()
    {
        ResolveBridgeFilePath();

        if (autoConnectOnStart)
        {
            Connect();
        }
    }

    public bool Connect()
    {
        ResolveBridgeFilePath();
        isConnected = true;

        if (verboseLog)
        {
            Debug.Log($"[FR5CSharpBridgeClient] Connected. Bridge file path: {resolvedBridgeFilePath}");
        }

        return true;
    }

    public void Disconnect()
    {
        isConnected = false;

        if (verboseLog)
        {
            Debug.Log("[FR5CSharpBridgeClient] Disconnected.");
        }
    }

    public bool PollLatestState()
    {
        if (!isConnected)
        {
            lastPollSucceeded = false;
            lastSampleValid = false;
            lastErrorMessage = "Client is not connected.";
            lastPollTime = DateTime.Now.ToString("HH:mm:ss");
            LogStatusIfChanged();
            return false;
        }

        if (string.IsNullOrWhiteSpace(resolvedBridgeFilePath))
        {
            lastPollSucceeded = false;
            lastSampleValid = false;
            lastErrorMessage = "Resolved bridge file path is empty.";
            lastPollTime = DateTime.Now.ToString("HH:mm:ss");
            LogStatusIfChanged();
            return false;
        }

        lastFileExists = File.Exists(resolvedBridgeFilePath);

        if (!lastFileExists)
        {
            lastPollSucceeded = false;
            lastSampleValid = false;
            lastErrorMessage = $"Bridge file not found: {resolvedBridgeFilePath}";
            lastPollTime = DateTime.Now.ToString("HH:mm:ss");
            LogStatusIfChanged();
            return false;
        }

        try
        {
            string json = File.ReadAllText(resolvedBridgeFilePath);
            FR5BridgeSampleJson raw = JsonUtility.FromJson<FR5BridgeSampleJson>(json);

            if (raw == null)
            {
                lastPollSucceeded = false;
                lastSampleValid = false;
                lastErrorMessage = "JSON parse result is null.";
                lastPollTime = DateTime.Now.ToString("HH:mm:ss");
                LogStatusIfChanged();
                return false;
            }

            FR5SdkPoseSample sample = new FR5SdkPoseSample();
            sample.isValid = raw.isValid;
            sample.source = string.IsNullOrWhiteSpace(raw.source) ? "CSharpBridge" : raw.source;
            sample.timestampSeconds = raw.timestampSeconds;

            for (int i = 0; i < 6; i++)
            {
                sample.jointDegrees[i] = (raw.jointDegrees != null && raw.jointDegrees.Length > i)
                    ? raw.jointDegrees[i]
                    : 0f;
            }

            sample.flangePositionMillimeters = ToVector3(raw.flangePositionMillimeters);
            sample.flangeRotationDegrees = ToVector3(raw.flangeRotationDegrees);
            sample.tcpPositionMillimeters = ToVector3(raw.tcpPositionMillimeters);
            sample.tcpRotationDegrees = ToVector3(raw.tcpRotationDegrees);

            sample.toolIndex = raw.toolIndex;
            sample.userIndex = raw.userIndex;
            sample.robotMode = raw.robotMode;
            sample.robotState = raw.robotState;
            sample.alarmCode = raw.alarmCode;

            latestSample = sample;

            lastPollSucceeded = true;
            lastSampleValid = sample.isValid;
            lastSampleSource = sample.source;
            lastRobotState = string.IsNullOrWhiteSpace(sample.robotState) ? "Unknown" : sample.robotState;
            lastPollTime = DateTime.Now.ToString("HH:mm:ss");
            lastErrorMessage = sample.isValid ? "None" : "Sample is invalid. Check bridge / robot connection.";

            LogStatusIfChanged();
            return true;
        }
        catch (Exception ex)
        {
            lastPollSucceeded = false;
            lastSampleValid = false;
            lastErrorMessage = ex.Message;
            lastPollTime = DateTime.Now.ToString("HH:mm:ss");

            Debug.LogError("[FR5CSharpBridgeClient] Failed to read bridge JSON: " + ex.Message);
            return false;
        }
    }

    public bool TryGetLatestSample(out FR5SdkPoseSample sample)
    {
        if (latestSample == null)
        {
            sample = FR5SdkPoseSample.CreateInvalid("CSharpBridge");
            return false;
        }

        sample = latestSample.Clone();
        return true;
    }

    /// <summary>
    /// Return a robot state label intended for UI panels.
    /// </summary>
    public string GetDisplayRobotStateLabel()
    {
        if (!isConnected)
        {
            return "Disconnected";
        }

        if (!lastFileExists)
        {
            return "Bridge File Missing";
        }

        if (!lastPollSucceeded)
        {
            return "Poll Failed";
        }

        if (string.IsNullOrWhiteSpace(lastRobotState))
        {
            return lastSampleValid ? "Ready" : "Unknown";
        }

        return lastRobotState;
    }

    /// <summary>
    /// Return a bridge message intended for UI panels.
    /// </summary>
    public string GetDisplayMessageLabel(string fallbackMessage)
    {
        if (!isConnected)
        {
            return "Bridge client is not connected.";
        }

        if (!lastFileExists)
        {
            return string.IsNullOrWhiteSpace(lastErrorMessage)
                ? "Bridge file not found."
                : lastErrorMessage;
        }

        if (!lastPollSucceeded)
        {
            return string.IsNullOrWhiteSpace(lastErrorMessage)
                ? "Bridge poll failed."
                : lastErrorMessage;
        }

        if (!lastSampleValid)
        {
            return string.IsNullOrWhiteSpace(lastErrorMessage)
                ? "Sample is invalid."
                : lastErrorMessage;
        }

        if (!string.IsNullOrWhiteSpace(fallbackMessage) && fallbackMessage != "Idle")
        {
            return fallbackMessage;
        }

        return "Bridge ready.";
    }

    private void ResolveBridgeFilePath()
    {
        resolvedBridgeFilePath = Path.Combine(
            Application.streamingAssetsPath,
            bridgeFolderName,
            bridgeFileName
        );
    }

    private Vector3 ToVector3(float[] arr)
    {
        if (arr == null || arr.Length < 3)
        {
            return Vector3.zero;
        }

        return new Vector3(arr[0], arr[1], arr[2]);
    }

    private void LogStatusIfChanged()
    {
        if (!verboseLog)
        {
            return;
        }

        string currentKey =
            $"{lastFileExists}|{lastPollSucceeded}|{lastSampleValid}|{lastSampleSource}|{lastRobotState}|{lastErrorMessage}";

        if (currentKey == previousLogKey)
        {
            return;
        }

        Debug.Log(
            "[FR5CSharpBridgeClient] " +
            $"FileExists={lastFileExists} | " +
            $"PollSucceeded={lastPollSucceeded} | " +
            $"Valid={lastSampleValid} | " +
            $"Source={lastSampleSource} | " +
            $"RobotState={lastRobotState} | " +
            $"Error={lastErrorMessage}"
        );

        previousLogKey = currentKey;
    }
}
